-- ============================================================
-- SEED DATA LENGKAP - MerchantTJD (111 merchants)
-- Generated: 2026-03-30 08:44:44
-- ============================================================

-- Reset data lama
DELETE FROM followup_history;
DELETE FROM visit_evidence;
DELETE FROM merchants;

INSERT INTO merchants (merchant_id, nama_merchant, pic, "3p", followup, jumlah_fu, tanggal_fu_terakhir, hasil_fu, potensi_nominal, edc_mandiri, created_at, updated_at)
VALUES
  ('TJD0001', 'ABUBA STEAK - TANJUNG DUREN', 'Ahmad Dika Widjaya', 'Pebisnis', 'Sudah', 4, '2026-03-26 16:35:05', NULL, NULL, false, NOW(), NOW()),
  ('TJD0002', 'MADAM LEE KOREAN BBQ TANJUNG DUREN', 'Amelia Andremica', 'Pebisnis', 'Sudah', 2, '2026-03-26 16:35:33', 'berminat', NULL, false, NOW(), NOW()),
  ('TJD0003', 'UENA (TANJUNG DUREN)', 'Danar', 'Pebisnis', 'Sudah', 1, '2026-03-04 00:00:00', 'Tidak Berminat', NULL, false, NOW(), NOW()),
  ('TJD0004', 'ALFAMART TANJUNG DUREN 3', 'Didik Setiawan', 'Pebisnis', 'Sudah', 1, '2026-03-04 00:00:00', 'Tidak Berminat', NULL, false, NOW(), NOW()),
  ('TJD0005', 'INDOMARET TANJUNG DUREN UTARA 4 TTNG', 'Henny Esteria Manalu', 'Pebisnis', 'Sudah', 1, '2026-03-04 00:00:00', 'Tidak Berminat', NULL, false, NOW(), NOW()),
  ('TJD0006', 'INDOMARET CENTRAL PARK', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Sudah', 1, '2026-03-04 00:00:00', 'Tidak Berminat', NULL, false, NOW(), NOW()),
  ('TJD0007', 'CHOIPAN DAN KALOCI PHO-PHO', 'Nurul Juwita Ningsih', 'Pebisnis', 'Sudah', 1, '2026-03-26 16:37:29', 'pikir-pikir dulu', NULL, false, NOW(), NOW()),
  ('TJD0008', 'BHINNEKA RASA', 'Olivia Sidabutar', 'Pebisnis', 'Sudah', 1, '2026-03-27 12:16:38', 'berminat', NULL, false, NOW(), NOW()),
  ('TJD0009', 'TOP VEGE', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0010', 'AYAM PENYET WONOGIRI', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0011', 'KOUFU MALATANG', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0012', 'FISH STREAT TANJUNG DUREN', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0013', 'NORDIC FAMILY SEAFOOD SUPPLIER', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0014', 'ONNI HOUSE JAKARTA', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0015', 'SOGOGI SHABU & GRILL TANJUNG DUREN', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0016', 'DUM DUM THAI DRINKS TANJUNG DUREN', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0017', 'CANTO SOCIAL DIMSUM', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0018', 'RUMAH MAKAN BPK NANGIN MILALA', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0019', 'FIRE POT HUBLIFE JAKARTA', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0020', 'WARTEG AYAM PENYET POJOK', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0021', 'ASAP SAMBAL ''SEI SAPI'' - TANJUNG DUREN', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0022', 'LOVING HUT EXPRESS', 'Didik Setiawan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0023', 'SOTO AYAM SEMARANG', 'Henny Esteria Manalu', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0024', 'SATU MEJA', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0025', 'PHO NGUYEN BY OLD QUARTER', 'Nurul Juwita Ningsih', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0026', 'SAN-G NONGKITIAM', 'Olivia Sidabutar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0027', 'WARTEG CEMARA', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0028', 'SUSHIGO! MALL TAMAN ANGGREK', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0029', 'SAIGON NGON', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0030', 'NAFISA MASAKAN ARAB', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0031', 'BEATRICE QUARTERS CENTRAL PARK', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0032', 'IMPERIAL KITCHEN & DIMSUM - MALL TAMAN ANGGREK', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0033', 'BURGER KING (CENTRAL PARK)', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0034', 'CHUAN XIANG PAVILION RESTAURANT', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0035', '% ARABICA JAKARTA CENTRAL PARK', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0036', 'JAVA KITCHEN - CENTRAL PARK', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0037', 'LETASU NEO SOHO', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0038', 'PARADISE DYNASTY - CENTRAL PARK', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0039', 'THE PEOPLE''S CAFE - CENTRAL PARK', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0040', 'EATON BAKERY AND RESTAURANT ( TAMAN ANGGREK )', 'Didik Setiawan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0041', 'IMPERIAL CHEF - MALL TAMAN ANGGREK', 'Henny Esteria Manalu', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0042', 'JIMBARAN SEAFOOD ULAM BALI', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0043', 'DAPUR SOLO - NEO SOHO', 'Nurul Juwita Ningsih', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0044', 'FOEK LAM CENTRAL PARK MALL', 'Olivia Sidabutar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0045', 'DIN TAI FUNG CHEF''S TABLE', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0046', 'YA KUN KAYA TOAST - MALL TAMAN ANGGREK', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0047', 'RIRIXIAN HOT POT @MALL TAMAN ANGGREK', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0048', 'NANNY''S PAVILLON CENTRAL PARK', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0049', 'SUSHI GO! CENTRAL PARK', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0050', 'CHONGQING LIUYISHOU HOTPOT MALL NEOSOHO"WE ARE MOVING"', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0051', 'DONER KEBAB', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0052', 'HOKBEN MAL TAMAN ANGGREK', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0053', 'BABY DUTCH PANCAKE NEO SOHO', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0054', 'MARUGAME UDON  NEO SOHO MALL', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0055', 'BEBEK TEPI SAWAH', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0056', 'GYU-KAKU JAPANESE BBQ - NEO SOHO', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0057', 'TAEYANG SUNG NEO SOHO', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0058', 'COMMON GROUNDS NEO SOHO', 'Didik Setiawan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0059', 'WENDY''S - NEO SOHO', 'Henny Esteria Manalu', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0060', 'FOGO BRAZILIAN BBQ - NEO SOHO', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0061', 'WINGSTOP - NEO SOHO', 'Nurul Juwita Ningsih', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0062', 'PUTIEN NEO SOHO', 'Olivia Sidabutar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0063', 'BORNGA NEO SOHO', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0064', 'DIFA KEBAB TANJUNG DUREN', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0065', 'PANCIOUS CENTRAL PARK', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0066', 'YONGDAERI NEO SOHO', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0067', 'SERIBU RASA CENTRAL PARK MALL', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0068', 'RASA BY COLLAGE', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0069', 'UD.YAMIN', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0070', 'NYONYA TAN', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0071', 'MARTABAK BANGKA 21 TANJUNG DUREN', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0072', 'CIRENG ISI NYONYA MENI PSRKOPRO', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0073', 'PEPPER LUNCH - CENTRAL PARK', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0074', 'SUBWAY - CENTRAL PARK', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0075', 'BUBUR AYAM #UPIN', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0076', 'BUBUR AYAM SHEILA', 'Didik Setiawan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0077', 'PINGOO NEO SOHO', 'Henny Esteria Manalu', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0078', 'THE PANCAKE CO. BY DORE HUBLIFE', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0079', 'FISH & CHEAP', 'Nurul Juwita Ningsih', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0080', 'DAILYBOX TANJUNG DUREN', 'Olivia Sidabutar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0081', 'SUSHI HIRO MALL TAMAN ANGGREK', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0082', 'YOSHINOYA TAMAN ANGGREK', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0083', 'STEAK 21 BUFFET TAMAN ANGGREK', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0084', 'TA WAN   MALL TAMAN ANGGREK', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0085', 'SATE KHAS SENAYAN TAMAN ANGGREK', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0086', 'PAIKS NOODLE MALL TAMAN ANGGREK Í™_x008d_Ì½©Ë°˜Ì _x0090_0410', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0087', 'PIZZA HUT RISTORANTE - MALL TAMAN ANGGREK', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0088', 'MI MIE DANG TAMAN ANGGREK', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0089', 'MARUGAME UDON MALL TAMAN ANGGREK', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0090', 'SUPERFOOD BAK KUT TEH', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0091', 'MARKETTE - CENTRAL PARK', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0092', 'REMBOELAN', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0093', 'MUTIARA CHINESE FOOD Å_x008f_£Ç¦_x008f_', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0094', 'ALLOFRESH CENTRAL PARK', 'Didik Setiawan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0095', 'SNACK CORNER INDONESIA', 'Henny Esteria Manalu', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0096', 'TOMANG TOL PASAR SWALAYAN SUPERMARKET', 'Ineu Fajri Pratiwi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0097', 'RIDWAN''S GROCERIES', 'Nurul Juwita Ningsih', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0098', 'TOKO ANDY', 'Olivia Sidabutar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0099', 'TOKO PLASTIK & SEMBAKO 89', 'Parlip', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0100', 'TOKO TONI', 'Rafly', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0101', 'TOKO SAWITRI ( PT. RAHARJA PANGAN LESTARI )', 'Raja Natalius Dava', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0102', 'GLOWINGMEERKAT', 'Rokieb', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0103', 'PTM POCI', 'Rusdi Sandi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0104', 'B FASHION HOTEL', 'Ruspika Situmorang', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0105', 'HOTEL BULEVAR TANJUNG DUREN JAKARTA', 'Selly Selmainiar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0106', 'GRAND TROPIC SUITES HOTEL JAKARTA', 'Sunardi', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0107', 'URBANVIEW HOTEL RESIDENCE 446 TANJUNG DUREN', 'Yola Rahma Suhada', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0108', 'MATHEW AIR NUSANTARA. PT', 'Zola Rauldhan', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0109', 'PATTI SEWA & RENTAL MOBIL JAKARTA', 'Ahmad Dika Widjaya', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0110', 'PT.FARTAN SKYTRAX AIR', 'Amelia Andremica', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW()),
  ('TJD0111', 'JA CONNECTION TAMAN ANGGREK', 'Danar', 'Pebisnis', 'Belum', 0, NULL, NULL, NULL, false, NOW(), NOW());

-- Verifikasi
SELECT COUNT(*) as total_merchants FROM merchants;
SELECT followup, COUNT(*) FROM merchants GROUP BY followup;
SELECT pic, COUNT(*) as total FROM merchants GROUP BY pic ORDER BY total DESC;